#---------------------------------------------------------------------------
Components = {'W21': {'shape': 'hexagon',
                      'material': 'W',
                      'side': '71.4598 mm',
                      'thickness': '2.1 mm',
                      'x': '0.0 mm',
                      'y': '0.0 mm',
                      'z': '0.0 mm'},
              
              'W42':  {'shape': 'hexagon',
                       'material': 'W',
                       'side': '71.4598 mm',
                       'thickness': '4.2 mm',
                       'x': '0.0 mm',
                       'y': '0.0 mm',
                       'z': '0.0 mm'},

              'Cu60': {'shape': 'hexagon',
                       'material': 'Cu',
                       'side': '71.4598 mm',
                       'thickness': '6.0 mm',
                       'x': '0.0 mm',
                       'y': '0.0 mm',
                       'z': '0.0 mm'},

              'WCu06': {'shape': 'hexagon',
                        'material': 'WCu',
                        'side': '71.4598 mm',
                        'thickness': '0.6 mm',
                        'x': '0.0 mm',
                        'y': '0.0 mm',
                        'z': '0.0 mm'},

              'Air30': {'shape': 'hexagon',
                        'material': 'Air',
                        'side': '71.4598 mm',
                        'thickness': '3.0 mm',
                        'x': '0.0 mm',
                        'y': '0.0 mm',
                        'z': '0.0 mm'},

              'Air60': {'shape': 'hexagon',
                        'material': 'Air',
                        'side': '71.4598 mm',
                        'thickness': '6.0 mm',
                        'x': '0.0 mm',
                        'y': '0.0 mm',
                        'z': '0.0 mm'},
              
              'Kapton':{'shape': 'hexagon',
                        'material': 'Air',
                        'side': '71.4598 mm',
                        'thickness': '0.01 mm',
                        'x': '0.0 mm',
                        'y': '0.0 mm',
                        'z': '0.0 mm'},

              'Si010': {'shape': 'hexagon',
                        'material': 'Si',
                        'side': '71.4598 mm',
                        'thickness': '0.10 mm',
                        'x': '0.0 mm',
                        'y': '0.0 mm',
                        'z': '0.0 mm'},

              'Si012': {'shape': 'hexagon',
                        'material': 'Si',
                        'side': '71.4598 mm',
                        'thickness': '0.12 mm',
                        'x': '0.0 mm',
                        'y': '0.0 mm',
                        'z': '0.0 mm'}
              }
#---------------------------------------------------------------------------
Geometry=['W42',
          'Air60',
          'W42',
          'Air60',
          'W42',
          'Air60',

          'W21',
          'Air60',
          'W21',
          'Air60',
          'W21',
          'Air30',

          'WCu06',
          'Cu60',
          'WCu06',
          'Kapton',
          'Si010',
          'Si010',
          'Si012']
